format = """
[](#393552)\
$username\
[](bg:#56526e fg:#393552)\
$directory\
[](fg:#56526e bg:#eb6f92)\
$git_branch\
$git_status\
[](fg:#eb6f92 bg:#ea9a97)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#ea9a97)\
$fill\
$time\n \
[\uf178](fg:#9ccfd8) \
"""


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#393552 fg:#9ccfd8"
style_root = "bg:#393552"
format = '[준]($style)'
disabled = false

[fill]
style = "fg:overlay"
symbol = " "

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"

[directory]
style = "bg:#56526e fg:#ea9a97"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#eb6f92 fg:#e0def4"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#eb6f92 fg:#e0def4"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#ea9a97"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#9ccfd8)]($style)'
